### ISSUE TITLE
Double icon

### ISSUE THREAD

**Issue by MikiDi** [kanselarij-vlaanderen/au-kaleidos-icons#2]
I came across `circle-question.svg` as well as `question-mark.svg`. They seem to contain the same thing.

**Comment by Wolfr** [comment]
Good catch, but do note when I created this package I added some things double as not to create too much stability problems on dev.

We could make a new version where we tackle the doubles and remove the legacy icons.

**Comment by brenner-company** [comment]
Opgelost met https://kanselarij.atlassian.net/browse/KAS-2921
